### ISSUE TITLE
租付通管理后台房源管理菜单——新增房源操作逻辑

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#1]
@wenpi commented on [Sat Sep 09 2017](https://github.com/cloudenergy/admin-zft-source/issues/1)

基于公寓业态的租付管理，核心是房源信息的采集，展现以及处理
![image](https://user-images.githubusercontent.com/3233385/30238225-830a970a-9575-11e7-8eb4-3b16ba6be1a2.png)
如图，实现房源信息的展现，添加以及相应的处理细节
添加如下图
![image](https://user-images.githubusercontent.com/3233385/30238259-37d03ac8-9576-11e7-8fb7-def416c6510e.png)
导入如附件
[房源信息导入模板.xlsx](https://github.com/cloudenergy/admin-zft-source/files/1289630/default.xlsx)

**Comment by zm60** [comment]
![image](https://user-images.githubusercontent.com/14212067/32586747-1fba0b3e-c4ca-11e7-9516-acadcf9f5319.png)
我们的房源展示界面大致就是这个样子了（详细标注我会另起任务），现在主要看右上角那个蓝色“添加”（房源）
![copy 4](https://user-images.githubusercontent.com/14212067/32586833-993e088e-c4ca-11e7-8573-4fd233f16f17.png)

![image](https://user-images.githubusercontent.com/14212067/32587183-83d4c4e0-c4cc-11e7-8bf9-099e362653b1.png)

**Comment by zm60** [comment]
添加房源：默认整租、1室1厅1卫，房源配置默认先全空着吧
![image](https://user-images.githubusercontent.com/14212067/32587344-83d630cc-c4cd-11e7-8ddb-770e3d7f0578.png)

**Comment by zm60** [comment]
选择合租后，户型默认2室1厅1卫，面板其他设置不变
![image](https://user-images.githubusercontent.com/14212067/32587780-f3d7e1de-c4cf-11e7-976a-1c364233a878.png)

**Comment by zm60** [comment]
添加整幢：默认如图7层，每层10间 1室1厅1卫 朝向东  ，尺寸标注按实际情况可微调。
![image](https://user-images.githubusercontent.com/14212067/32589477-52331906-c4da-11e7-947e-2a59d44d0e08.png)
下图示例为已编辑好信息：
![image](https://user-images.githubusercontent.com/14212067/32589570-dd5b4300-c4da-11e7-8e01-cae41e168f27.png)
