### ISSUE TITLE
针对公寓租务产生相应费用逻辑

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#10]
租付通系统对公寓租务有两种费用的产生
一是  计量仪表按刻度用量*单价产生费用，在公寓基本上只有电费
二是   运营者按出租实际情况按一定时间区域定义的固定费用，比如月租金，月水费，月杂费或者日租金，日水费，日杂费之类的

费用的支付在租付通系统有两种形式，
一种是预付费，意思是类同于电话费先充一笔钱，系统按产生的这都是费用或者日杂费按天扣除，不够就通知

一种是后付费，意思是类同于支付宝上支付水电租金账单，先生成账单，租户在移动端完成支付

由公寓运营方设置  后付费账单是否可以在预付费账户上自动代扣，代扣规则类同于支付宝自动还信用卡，付水电费的逻辑。

这四种行为都要在租务合同上完成定义
![image](https://user-images.githubusercontent.com/3233385/33010120-4895ac36-ce14-11e7-8684-0eb29bc8caa1.png)

**Comment by kpse** [comment]
正常费用的意思就是 支持N元／月 的计算方式， 有账单，可以随租金付，N月一付，一次付清

电费因为有表，所以是特殊的，允许预付费；但是也可以配成和其他费用一样的后付费。

预付费费用代扣 项目有一个统一设置。允许在每个合同里面覆盖。
