### ISSUE TITLE
租付通关于水电煤等仪表计量处理

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#12]
![image.png](https://images.zenhubusercontent.com/5715c17dbf93871ccd99a8f3/6854b183-1cf1-4f14-865a-b5d2ac9a6d15)

按出租单元（room）显示相对应水电煤气表的自动读数，人工填入读数，财单支付租客，及历史读数，账单情况

按出租单元（room）统一设置水电煤气的单价，并且可以延伸到多选房源

@zm60  完成细节  @ZSH-HSZ  完成流水后，进行此项工作

**Comment by zm60** [comment]
参考墨刀：“抄表”模块  https://pro.modao.cc/app/11b16a4e26d5173699d915b6262704623563264c
