### ISSUE TITLE
关于仪表分摊的设计

### ISSUE THREAD

**Issue by Lautitia** [cloudenergy/web-zft#19]
当前分摊比例可以手动配置/自动分摊，而分摊又是需要跟随合同一起执行，那么会存在以下几种情况：
1。在所有合同都在履行中时，有权限的管理人员可以手动更改分摊配置
2。会导致合同中对于分摊的表述无法明确只能用类似“仪表分摊随同房屋中承租人员变动而变动
基于以上这些情况，我觉得会造成以下的问题：
1。合同概念的不一致性（分摊其实也是合同的一部分）
2。手动配置功能的放开导致的分摊配置的管理困难（有权限的管理员随时可以改动分摊比例）
从而造成从业务上无法清晰表述分摊与合同的逻辑关系，并且会对合同的业务造成影响(合同的不确认性会加大平台逻辑的复杂度以及影响合同的电子化)，介于此，我建议业务逻辑做如下修改：
1。一个房屋中，只要存在有执行中的合同，则无法新加房间(room)
2。在合同签定时，就在合同中写明，有1，2，3，N个人合租时，分摊比例是多少(N=房间数量)，如
1人独租时：100%
2人合租时：50%
。。。
Y人合租时：X%
（注：当Y=3*x(x<=N/3)时需要进行平均补足(比如3个时需要有一个为34%才能满足100%)，可使用最小用户id/最小roomId/每个house第一间room 等机制来承担需补足的费用）
3。房屋单价应有2套（公寓价/租户价）仪表单价默认从租户价设置中继承，但合同执行期间，单价以合同签定时为准，房屋单价如有变动，（公寓价直接体现在每日结算中,每日结算即时生效，租户价则应该在新签合同中体现），这样可以帮助公寓合算能耗

以上提议目的是为了贯彻合同的不可变更性和表述准确性，以及简单一致的逻辑方便用户的使用和理解

案例：
假设现在有房屋A，内有3间房间R1/R2/R3，则在R1签定合同时，关于分摊部分描述如下
默认为自动分摊（情况1），则有：
1人合租时:100%
2人合租时:50%
3人合租时:34%
或者人工指定分摊（情况2），则有：
1人合租时:100%
2人合租时:40%
3人合租时:30%
那么在R2签定合同时，关于分摊部分基于（情况1）有：
1人合租时:100%
2人合租时:50%
3人合租时:33%
基于（情况2）有：
1人合租时:100%
2人合租时:30% （可填范围 0-60）
3人合租时:30% (可填范围 0-70)
最后R3在签定合同时，基于（情况1）有：
1人合租时:100%
2人合租时:50%
3人合租时:33%
基于（情况2）有：
1人合租时:100%
2人合租时:30% （只可填30，满足100）
3人合租时:40% (可填40，满足100)

**Comment by huwenshu** [comment]
跟着承租情况自动平摊  计算分摊，充许管理员人工修改比例
