### ISSUE TITLE
配置三个分支的自动部署

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#2]
测试分支

预发布分支

线上分支

三个分支的自动部署

分支名由@kpse 定义

部署脚本由@weichenqi 完成

**Comment by kpse** [comment]
测试分支 master
预发布分支 preprod
产品分支 prod

**Comment by kpse** [comment]
问个问题，这些分支包含api的部署么？

**Comment by kpse** [comment]
完成develop分支到http://testzft.cloudenergy.me 的自动部署。
