### ISSUE TITLE
app中信息模块补缺

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#30]
详细交互见：https://pro.modao.cc/app/f630f4f1ca959983e49e5661203dcb6956f50b79#screen=s7e4a5883e821c7d29914a0 

页图效果
![image](https://user-images.githubusercontent.com/3233385/39079996-4e1f9606-4558-11e8-949b-349b48508b82.png)
app推送没有接口供信息模块获取信息，无法点击打开，本应该
![image](https://user-images.githubusercontent.com/3233385/39080001-6dbf5848-4558-11e8-9b25-d25f91e0e20d.png)

然后每一条信息可以app内打开详情，点击去相应的充值支付或者账单支付页面

**Comment by kpse** [comment]
app已经修改，等待出包 @ZSH-HSZ 出新包
