### ISSUE TITLE
电小鸽-创建合同显示优化

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#32]
1、合同编号为必填选项，页面显示为选填。
2、必填选项字符为空或不符合规范内容主动提示错误。
3、增加租户账号重复判断提示。已在系统内使用过的登录账号再次创建无提示信息
如：
合同编号内容为数字+字母组合或纯数字(hzk20180503、20180503)，填入中文字符串主动提示错误。
![default](https://user-images.githubusercontent.com/27998601/39586841-ab596cd0-4f2a-11e8-8deb-6351dcd215ec.png)

**Comment by DXcheng** [comment]
![default](https://user-images.githubusercontent.com/27998601/39587317-c81afd42-4f2b-11e8-9419-6388e15fdb38.png)

**Comment by ZSH-HSZ** [comment]
@DXcheng  没有这个需求，请关闭 @kpse
