### ISSUE TITLE
租户充值，提示充值失败。

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#37]
![image](https://user-images.githubusercontent.com/27998601/39738677-096814ec-52bf-11e8-9b68-9ccaf566eda7.png)

**Comment by ZSH-HSZ** [comment]
后台用户表混乱，等周毅 更新用户表 @DXcheng  @kpse

**Comment by kpse** [comment]
已部署产品。请 @DXcheng  验收
