### ISSUE TITLE
承租输入合同信息操作

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/web-zft#4]
@wenpi commented on [Sat Sep 09 2017](https://github.com/cloudenergy/admin-zft-source/issues/2)

如下图：
![image](https://user-images.githubusercontent.com/3233385/30238381-3f699cae-9579-11e7-8b48-fde4d9edcc5c.png)
完成租户对房源的预订与承租的操作

**Comment by zm60** [comment]
![image](https://user-images.githubusercontent.com/14212067/32597726-2921b5c2-c4fd-11e7-949d-e216fcaa2243.png)

**Comment by zm60** [comment]
在房源展示页点击右上角蓝色“+添加”——“租户”

![copy 4](https://user-images.githubusercontent.com/14212067/32597782-5586b3f6-c4fd-11e7-9860-acbc6f8bf002.png)

**Comment by zm60** [comment]
弹窗添加租户，创建用户账号，用户信息，设置租约。
![group 142](https://user-images.githubusercontent.com/14212067/32598944-a7a54f96-c500-11e7-825f-49e7cd54b10d.png)

**Comment by zm60** [comment]
“添加租户”内容细节
![group 143](https://user-images.githubusercontent.com/14212067/32599096-11035cc6-c501-11e7-9848-75312278de1e.png)

**Comment by kpse** [comment]
@Lautitia 提供后台接口实现。

**Comment by kpse** [comment]
https://app.swaggerhub.com/apis/Lautitia/ZFT/v1.0#/
接口定义
