### ISSUE TITLE
电小鸽-信息推送功能缺失

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#43]
1、新建合同，用户登录信息系统默认主动推送至合同内预留手机号。登录密码默认：123456
2、欠费、预警消息渠道：APP、微信公众号、短信
3、充值消息渠道：APP、微信公众号
4、停止服务消息（断电切闸）：APP、微信公众号、短信
帐号消息推送为创建合同完成后实时推送。
备注：欠费消息随结算时间推送（结算时间为次日8：00，次日8时计算前日00：00至00：00总费用）

**Comment by kpse** [comment]
已实现：
1、新建合同，用户登录信息系统默认主动推送至合同内预留手机号。登录密码默认：123456

和 账单欠费 通知

其他还要做什么，请整理优先级 @DXcheng

**Comment by DXcheng** [comment]
1、关闭房租预期消息推送包括短信、APP通知消息
2、启用欠费消息推送、包括短信、APP通知消息

**Comment by kpse** [comment]
去掉 房租逾期
加上 欠费短信
