### ISSUE TITLE
电小鸽-预付费账单无扣费记录

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#52]
1、对仪表扣费记录显示
2、对合同附加费用显示如：税费、管理费、停车费等

![image](https://user-images.githubusercontent.com/27998601/40279159-37a251fa-5c70-11e8-8ed9-ce39d339f712.png)

**Comment by ZSH-HSZ** [comment]
税费、管理费、停车费等系统中没有

**Comment by ZSH-HSZ** [comment]
@kpse  仪表扣费是没有电费使用或者没有扣费呢

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/40279204-ef242268-5c70-11e8-8135-f7595b5240f8.png)
请仔细看合同附加费用栏目

**Comment by ZSH-HSZ** [comment]
这不是预付费

**Comment by kpse** [comment]
- 费用=每天0点到23点每小时差值*单价
- 账单=费用-用户余额
- 每天计算一次

合同内的附加费用策略 另开问题考虑， 请 @DXcheng @zm60 继续细化

**Comment by kpse** [comment]
- 预付费扣费逻辑已完成。
- 分摊后台逻辑已完成。
- 不包含合同相关附加费，
- 接下来要做的是禁用前端创建合同相关字段。

@DXcheng
