### ISSUE TITLE
电小鸽-房间仪表绑定信息无仪表备注显示

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#53]
![image](https://user-images.githubusercontent.com/27998601/40279193-ae58498a-5c70-11e8-8c54-be786e49018a.png)

**Comment by ZSH-HSZ** [comment]
没有备注显示什么啊

**Comment by ZSH-HSZ** [comment]
![image](https://user-images.githubusercontent.com/31639046/40279206-0253a840-5c71-11e8-8798-8e4312625d98.png)

**Comment by DXcheng** [comment]
电小鸽的测试流程在线上，你要明白？当初提出在ISSU上的跟踪也是基于线上的，你天天看test上的截图，又不推上线你想证明什么呢？给你自己看？

**Comment by ZSH-HSZ** [comment]
请 @kpse 在house接口的device 和room的device 返回设备备注memo

**Comment by kpse** [comment]
已部署产品，请 @DXcheng 验收

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/40663560-819beefc-638b-11e8-845b-c2bbf40d6719.png)
创建合同绑定仪表后，仪表备注无显示
