### ISSUE TITLE
电小鸽-分摊定义功能逻辑

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#54]
1、房间内绑定电表默认为分摊电表
2、分摊电表用量以百分比形式展现，系统根据房间合约有效性平均计算房间所承百分比
3、百分比除不尽时默认该房源循序第一间承担34%比例
（如：房间以A,B,C,D排序。A B  C入住，则A房间承担34% B、C承担各33%。如A房间退租，B,C自动调整为各50%  D房间入住A房间保持空置状态，则B承担34% C、D房间承担各33% ）
4、分摊比例根据房间合同有效性及时为系统默认平均分摊模式。解释：房间合约状态变化时（增加新租户，旧租户退租），无论用户时候有自定义分摊计划，所有房间重新均分分摊比例
5、逾期房间继续保留分摊比例，直至退租结算。
6、分摊比例可人工修改，比例调整总和必须保证100%
7、0%输入判断为输入错误
8、分摊输入框做字符录入判断，只可输入阿拉伯数字、数字为整数。

**Comment by kpse** [comment]
请根据目前实现的功能 提意见 @DXcheng

**Comment by kpse** [comment]
2，6，7，8 已实现。

**Comment by kpse** [comment]
5 已实现。 请验收 @DXcheng
