### ISSUE TITLE
增加一个海兴域名SSL访问电小鸽

### ISSUE THREAD

**Issue by huwenshu** [cloudenergy/web-zft#55]
按对接群里提交的ssl文件，在电小鸽saas系统nginx上增加一个corp.hxgroup.cn域名访问配置

@kpse  完成后 请提交https://corp.hxgroup.cn 访问截图

**Comment by kpse** [comment]
如果按你的方案配置，最后访问成功的页面上没有关于 corp.hxgroup.cn 的任何信息

**Comment by kpse** [comment]
已部署，请 @huwenshu 验收
