### ISSUE TITLE
增加取海兴仪表数据接口

### ISSUE THREAD

**Issue by huwenshu** [cloudenergy/web-zft#56]
基于海兴仪表采集器以及NB表硬件直接对接问题良好，现采用直接对接海兴API方式来取海兴仪表数据，对接接口：http://115.238.36.165:29001/

对接协议如附件
[智慧云智能表API接口v3.3.pdf](https://github.com/cloudenergy/web-zft/files/2033725/API.v3.3.pdf)

@kpse  api取仪表数据  类同于当前collector对接硬件

这个对接的意义需要建立在电小鸽系统能正常使用的情况下，不然对接了他们的表也没地方使用，优先顺序由 @DXcheng 协商

验收条件是海兴的仪表，能正常在电小鸽系统抄读，远程控制

**Comment by DXcheng** [comment]
1、优先对接现有线上租付通系统。
2、利用现有仪表导入逻辑，海兴api获取的仪表，先进入服务器再根据每个项目导入仪表id归属仪表所属项目。
3、接口内只对，仪表读数、名称、通讯时间、开关状态做显示。
4、仪表归属类型“电表”

**Comment by kpse** [comment]
- 仪表读数的频率是多少 每小时，每天？3分钟？
- 涉及接口： 
  * 读数 /api/business/devicedata
  * 拉闸 /api/control/send
  * 状态获取 /api/network/info
  * 登陆 /api/register/login

**Comment by kpse** [comment]
完全阻塞，无进展。

**Comment by DXcheng** [comment]
新版接口3.6
[Uploading 智慧云智能表API接口v3.6--河洛章纹请教--20180605.docx…]()

**Comment by kpse** [comment]
- /api/register/login 
- /api/business/devicedata
- /api/network/info
这三个接口能用了。

- /api/control/send
开关设备命令还是超时，等待海兴修复。

**Comment by kpse** [comment]
- /api/sensor/info 
这个接口也能用了。

**Comment by kpse** [comment]
- /api/control/send 
断断续续也能用了

**Comment by kpse** [comment]
海兴的设备给的ID 这个样子。EM300000000587
需要截断只要数字么？

**Comment by kpse** [comment]
抄表 写数据库deviceheartbeats, devicedata, deviceChannels, devices  实现了，接下来要做：
- 一个项目多个账号
- 控制命令下发

**Comment by kpse** [comment]
完成 一个项目多个账号

**Comment by kpse** [comment]
控制命令下发已完成。
功能已部署产品， 请验收 @DXcheng
