### ISSUE TITLE
电小鸽-附加费费用输入栏增加字符判断

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#58]
1、限制金额最大为小数点后2位
2、限制输入中文字符、字母、特殊符号、数字+字母（2F2）

![image](https://user-images.githubusercontent.com/27998601/40663341-00172568-638b-11e8-8b63-e6a3d97a6d87.png)

**Comment by DXcheng** [comment]
预付费显示“元/日”

**Comment by kpse** [comment]
已部署测试服和产品 ，请 @DXcheng 验收
