### ISSUE TITLE
电小鸽-费用账单预付费扣费字段修改

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#59]
1、扣费类型：支持合同附加费用内所有类型
2、消费金额（元）数字显示为红色
3、剩余金额（元）负数显示为红色，正数为黑色
所有金额数据精确小数点后2位，不做四舍五入
![image](https://user-images.githubusercontent.com/27998601/40713743-44880f0c-6433-11e8-90e5-480eca459570.png)

**Comment by kpse** [comment]
已部署产品。等待31号凌晨数据测试。 @DXcheng

**Comment by DXcheng** [comment]
缺少公区分摊类型：公摊电费 分摊数据为0 页面照常显示
