### ISSUE TITLE
电小鸽-房间电费单价显示与实际设置单价显示不一致

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#60]
1、房间单价设置1.2元。预览房间仪表显示单价为1.00元

我好像传不了图…………

**Comment by kpse** [comment]
请上传图片

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/40841039-9dc664b6-65db-11e8-84f1-2db1f94a1de7.png)
![image](https://user-images.githubusercontent.com/27998601/40841046-a51d8bf4-65db-11e8-940e-c191d6ed36ab.png)
