### ISSUE TITLE
电小鸽（后台）-新增导入仪表接口，解决仪表归属项目问题。

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#62]
功能目的：
解决第三方API接入系统，仪表归属项目问题。

1、导入仪表以表格形式编辑导入
2、表格内导入仪表做重复判断，对已经存在其他项目内的仪表主动提示
3、针对不同仪表通讯协议，和协议位数不一致问题。仪表信息暂定为12位数字，不足位系统在仪表前方以0补齐位数自动处理。并归入系统“为绑定仪表”栏目显示相关信息
比如：仪表ID为“3”，自动补位为：000000000003
           仪表ID为：18012471241 自动补位为：“01812471241”
4、导入仪表做字符判断如：英文字符、特殊字符、特殊符号、数字+符号、数字+字母 均主动提醒修改导入失败
5、系统附带可下载导入模板
![image](https://user-images.githubusercontent.com/27998601/40788341-67073b30-6522-11e8-8c29-7400f196fa85.png)

**导入表格格式：**

![image](https://user-images.githubusercontent.com/27998601/40789028-0a2fce2a-6524-11e8-966b-13b0f156a612.png)

**Comment by kpse** [comment]
<img width="891" alt="screen shot 2018-06-04 at 11 29 09 pm" src="https://user-images.githubusercontent.com/790027/40920216-39a2dbc4-684f-11e8-9c70-d03fca3344b7.png">
设计一下导入规划框的界面。 @DXcheng

**Comment by kpse** [comment]
还有一点，因为你的字段就两个，所以所有仪表都默认是YTL的。

**Comment by kpse** [comment]
已部署产品，请验收。

**Comment by kpse** [comment]
加了YTL前缀，部署产品了

**Comment by kpse** [comment]
2号 驱动 HaiXing/Electric/Q-GDW-2013.js
这种设备导入时加`HX` 前缀，注意跨项目判断重复。

**Comment by kpse** [comment]
已部署产品。 @DXcheng
