### ISSUE TITLE
电小鸽（界面）-新增房源增加“电费单价”字段

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#75]
1、单价选项为必填字段
2、单价精确为小数点后2位，不做四舍五入处理
3、只可输入数字，对特殊字符、文字字母、数字+符号字母自动过滤。并提示错误
4、房间单价自动映射至单价设置内房间单价
![image](https://user-images.githubusercontent.com/27998601/41036921-3f04be4a-69c4-11e8-8004-55549ebc2318.png)
房间单价界面
![image](https://user-images.githubusercontent.com/27998601/41037184-12be2c26-69c5-11e8-9a1b-a5e6014c4387.png)

**Comment by jcouyang** [comment]
@DXcheng 这个字段能放别的地方吗？城市和区域是一个vue组件，加电费进去语义很奇怪
