### ISSUE TITLE
电小鸽-推送短信内容与系统显示信息不符

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#79]
1、短信内容显示房租账单逾期，系统查询并无预期提示
![image](https://user-images.githubusercontent.com/27998601/41073928-29dcf75c-6a38-11e8-887a-1965b158bed8.png)
短信显示
![image](https://user-images.githubusercontent.com/27998601/41074242-a9f6c9a8-6a39-11e8-8c13-6f522bb08b12.png)

**Comment by kpse** [comment]
赵世浩已修改，等待发包。

**Comment by kpse** [comment]
此问题是否还存在。 @DXcheng
