### ISSUE TITLE
电小鸽（boss）-电小鸽管理平台页面移植租付通后台界面。

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#80]
详情见附件：
[电小鸽BOSS界面功能方案.pdf](https://github.com/cloudenergy/web-zft/files/2080846/BOSS.pdf)

**Comment by wenpi** [comment]
直接移植boss.gugecc.com

**Comment by kpse** [comment]
@jcouyang 请尽快搭起前端框架，打通钱后端数据，然后分首页的样式任务给 @jQChou

**Comment by jcouyang** [comment]
@kpse api能列一下首页chart用到的api endpoint吗

**Comment by jcouyang** [comment]
- [X] 框架
- [X] build pipeline
- [X] login page
- [ ] dashboard
- management
  - [ ] 项目管理
  - [ ] 账号管理
  - [ ] 事件配置
  - [ ] 平台财务

**Comment by jcouyang** [comment]
@DXcheng 首页那几个数据能更详细定义下吗？比如
- 汇总的时间区间是多少？
- 柱状图是按多长时间group
- 排名显示前几
- 事件显示几条

**Comment by DXcheng** [comment]
1、汇总区间分2个饼图，饼图一为当日充值途径统计，饼图二为当月、年充值途径统计，年、月数据可切换条件显示，默认为月
2、柱状图为间隔时间为1小时
3、排名显示前10名，以移动端充值途径为主数据
4、充值时间默认展开20条（看界面长度可调整数量），不做历史查询或者下拉边框显示，第一条默认为最新充值时间，当前页面自动更新，不需刷新整页数据

**Comment by jcouyang** [comment]
1.
<img width="503" alt="e3e598bd-2874-40c1-96af-5ed328261f13" src="https://user-images.githubusercontent.com/1235045/41975772-0379e6ec-7a5f-11e8-9d01-6dadcc03c529.png">

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/41978652-d8050366-7a54-11e8-9060-f9a3cb5f5249.png)

**Comment by jcouyang** [comment]
3 是什么意思？饼图单位是元？
pdf里写的是充值途径占比，这是收入，到底哪个？@DXcheng

**Comment by DXcheng** [comment]
1、首页饼图除去现金充值渠道显示，保留现金统计API，后期再另外显示。
其他模块按照数字顺序陆续做完，有不懂的群里问
1、首页
2、项目管理
3、账号管理
4、事件配置
5、平台财务
