### ISSUE TITLE
电小鸽-部署电小鸽app二维码下载网盘

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#85]
1、用户可扫码下载电小鸽app（含ios、安卓）
下载二维码提交至楼下⬇️

**Comment by kpse** [comment]
我不知道安卓发布到哪里了 @huwenshu

**Comment by kpse** [comment]
等待安卓 APP发布。

**Comment by kpse** [comment]
安卓URL：https://exg-app.oss-cn-beijing.aliyuncs.com/exg-app-latest.apk
iOS URL：https://itunes.apple.com/cn/app/id1365519317?mt=8
下载页面： http://zft.gugecc.com/exg-app.html

等待下载页面部署。

**Comment by kpse** [comment]
exg-app已部署。请验收 @DXcheng
