### ISSUE TITLE
电小鸽-制作电小鸽二维码充值流程图

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#86]
1、具体参租付通扫码充值流程图，提供app下载二维码、微信公众号二维码
2、二维码对接人赵直接找索勤

**Comment by kpse** [comment]
下载页面应为： http://zft.gugecc.com/exg-app.html 
等待部署。

**Comment by kpse** [comment]
![Uploading QR_Code_exg-app.png…]()

**Comment by kpse** [comment]
[二维码](https://exg-app.oss-cn-beijing.aliyuncs.com/QR_Code_exg-app.png)
