### ISSUE TITLE
电小鸽-新建房源信息做当前页面及时刷新显示

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#88]
创建房源结束，当前页面房源信息、数量需刷新本页后才显示房源信息名称及数量
1、正确交互体验建立房源信息，小区显示栏目对小区名称、数量做及时刷新显示处理

![image](https://user-images.githubusercontent.com/27998601/41730261-fcfc65ac-75ad-11e8-99ad-dff77f2fe21e.png)

**Comment by kpse** [comment]
部署一版修改 到测试服。 @DXcheng
