### ISSUE TITLE
电小鸽（页面）-房间卡片房间朝向显示错误

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#90]
1、创建房源信息朝向默认为：南，房间卡片显示为：北

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/41731384-de59fe04-75b0-11e8-91ae-b73929e1b928.png)

**Comment by kpse** [comment]
已部署产品 @DXcheng
