### ISSUE TITLE
电小鸽-房源分摊逻辑、显示优化

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#97]
1、分摊逻辑以房源内房间有效性为分摊比例计算，
分摊原则：退租或新增房源，分摊界面则根据实际有效房间，只对有效房间显示比例；
2、去除房源内“删除”按钮，对于房间内解绑表操作在房间信息内完成；
3、改更原分摊字段显示；

**Comment by kpse** [comment]
已部署产品 @DXcheng
