### ISSUE TITLE
电小鸽-账号提现申请优化

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#98]
![image](https://user-images.githubusercontent.com/27998601/42883035-05dca2a2-8acd-11e8-96fe-fc0915e6107d.png)

1、对已经提交银行卡信息申请审核的项目，系统记录提交状态并区分出申请状态。
A、未提交申请显示为：可填入信息，状态显示“提交申请”
B、已经提交申请未审核通过的显示：审核失败
C、已经提交申请并未审核显示：审核中
D、已经提交申请并审核成功显示：审核成功

**Comment by DXcheng** [comment]
审核成功状态当前以灰色显示显示已经审核的信息内容
![image](https://user-images.githubusercontent.com/27998601/42883388-16f6983a-8ace-11e8-8ce6-1be0dbf780ea.png)

**Comment by kpse** [comment]
@DXcheng boss的需求提到boss的库里面去吧？ (boss)[https://github.com/cloudenergy/boss]

**Comment by jcouyang** [comment]
这不是boss的, 就是这的

**Comment by jcouyang** [comment]
> 对已经提交银行卡信息申请审核的项目
意思是银行卡号是ID?还是卡号+姓名?

**Comment by jcouyang** [comment]
@DXcheng 已部署产品
