### ISSUE TITLE
电小鸽-提现金额逻辑优化

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/web-zft#99]
1、对各充值途径金额过滤，区分出线上、线下充值金额汇总
2、提现余额定义：线上途径充值，并扣费平台手续费的总金额

**Comment by kpse** [comment]
再细化一下描述，看不懂需求。 @DXcheng

**Comment by kpse** [comment]
只统计在线渠道充值， 然后乘一个 0.994

**Comment by kpse** [comment]
已部署产品，请验收 @DXcheng
